### ISSUE TITLE
Problems during the AlphaCodium installation process

### ISSUE THREAD

**Issue by JeehoonLim** [Codium-ai/AlphaCodium#27]
HI

I encountered  some problems  during the AlphaCodium installation process.

- OS : MacOS Sonoma 14.3
- Python : 3.12.1
 
When I executed the command < pip install -r requirements.txt >, I got error logs like below : 

> Collecting PyYAML==6.0 (from -r requirements.txt (line 12))
  Downloading PyYAML-6.0.tar.gz (124 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 125.0/125.0 kB 11.7 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [54 lines of output]
      running egg_info
      writing lib/PyYAML.egg-info/PKG-INFO
      writing dependency_links to lib/PyYAML.egg-info/dependency_links.txt
      writing top-level names to lib/PyYAML.egg-info/top_level.txt
      Traceback (most recent call last):
        File "/Users/jholim/workspace/codeai/demo/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/Users/jholim/workspace/codeai/demo/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/Users/jholim/workspace/codeai/demo/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/k8/27k28wmn09j3109z45qxk9xr0000gn/T/pip-build-env-gondi16m/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 325, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
       
I passed that point using the following information, but other issues arose.
- https://discuss.python.org/t/getting-requirements-to-build-wheel-did-not-run-successfully-exit-code-1/30365

Could you give some advise that I can solve this problem?
Or, please let me know your environment info - including python version.

Thanks in advance.

**Comment by mrT23** [comment]
I have no idea. I suspect it has something with your new Mac OS, and the package that comes with it.

Try with Python 3.10 instead. this is what I am using, and I am able to build, as do others.

**Comment by mrT23** [comment]
also try this
https://github.com/Codium-ai/AlphaCodium/pull/28

**Comment by JeehoonLim** [comment]
Thanks @mrT23 .
It solved with one more update fordackdb.
With  latest commit (https://github.com/Codium-ai/AlphaCodium/commit/be70a65f81816488b5aa4e03c2545ac2387faed9),  I got error like below.

> ERROR: Could not find a version that satisfies the requirement duckdb==0.9.3.dev3077 (from versions: 0.0.0, 0.0.2, 0.0.3, 0.1.0, 0.1.1, 0.1.2, 0.1.3, 0.1.5, 0.1.6, 0.1.7, 0.1.8, 0.1.9, 0.2.0, 0.2.1, 0.2.2, 0.2.6, 0.2.7, 0.2.8, 0.2.9, 0.3.0, 0.3.1, 0.3.2, 0.3.3, 0.3.4, 0.4.0, 0.5.0, 0.5.1, 0.6.0, 0.6.1, 0.7.0, 0.7.1, 0.8.0, 0.8.1, 0.9.0, 0.9.1, 0.9.2, 0.9.3.dev3257, 0.9.3.dev3465, 0.9.3.dev3597, 0.9.3.dev3623, 0.9.3.dev3715)
ERROR: No matching distribution found for duckdb==0.9.3.dev3077

I changed duckdb version from 0.9.3.dev3077 to 0.9.3.dev3715, it worked out.
