### ISSUE TITLE
Hello, I noticed that while running AI tests, some tests were mistakenly marked as failed due to timeouts. Upon reviewing the code, I found that the timeout duration is set to 3 seconds and it is not configurable.

### ISSUE THREAD

**Issue by zte-yangjizhe** [Codium-ai/AlphaCodium#33]
Hello, I noticed that while running AI tests, some tests were mistakenly marked as failed due to timeouts. Upon reviewing the code, I found that the timeout duration is set to 3 seconds and it is not configurable.
![image](https://github.com/Codium-ai/AlphaCodium/assets/152255029/aaedf898-3952-4523-ba25-64fc28ad0bc5)
However, when I run this test case individually with the generated code, the result is as expected, it's just that the execution time is a bit long.

**Comment by zte-yangjizhe** [comment]
![image](https://github.com/Codium-ai/AlphaCodium/assets/152255029/cb77e69e-8b23-4bd2-ae91-9ebdd137c1e9)

**Comment by mrT23** [comment]
A proper efficient solution should solve each problem in far less than 3 seconds.

This is a requirement from codeforce - they want to avoid brute force unoptimized solutions.

**Comment by zte-yangjizhe** [comment]
Oh, I see. Thank you very much for the explanation.
