### ISSUE TITLE
Support for Claude 3

### ISSUE THREAD

**Issue by gavrielc** [Codium-ai/AlphaCodium#42]
Can AlphaCodium run on Claude 3 Opus?

It would be great to see how AlphaCodium using Claude 3 performs compared to AlphaCodium using GPT-4

**Comment by mrT23** [comment]
done
https://github.com/Codium-ai/AlphaCodium?tab=readme-ov-file#news-2024-17-05

**Comment by gavrielc** [comment]
@mrT23 This is amazing! 
I think many people will be interested in seeing how the models compare on AlphaCodium.

Can you add data labels to the leaderboard chart so that it's possible to easily see the exact percentage for each model?

**Comment by mrT23** [comment]
good idea, added

To be honest, i was disappointed from Claude3.  I thought it would do better.
and given the fact it is slower and more expensive than GPT4, I don't think Anthropic are quite there yet in terms of competition for code models.
